#!/bin/bash
#
# Perform necessary redmine setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

/opt/redmine/embedded/bin/ruby /opt/redmine/embedded/service/redmine/script/rails server webrick -e production

echo "Thank you for installing redmine!"

exit 0
