#!/bin/bash
#
# Perform necessary redmine setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Create needded dir for postgres
mkdir -p /opt/redmine/embedded/data/pg_tblspc 
mkdir -p /opt/redmine/embedded/data/pg_twophase 
mkdir -p /opt/redmine/embedded/data/pg_stat_tmp
touch  /opt/redmine/embedded/data/pg_stat_tmp/pgstat.tmp

# Change to user permission
chown $USER:$USER /opt/redmine -R

# Start the database
/opt/redmine/embedded/bin/postgres -D /opt/redmine/embedded/data -p 5433 &

# Start the application
/opt/redmine/embedded/bin/ruby /opt/redmine/embedded/service/redmine/bin/rails server webrick -e production &

echo "Thank you for installing redmine!"

exit 0
